spring:
  application:
    name: CrpytoService
  data:
    mongodb:
      uri: mongodb+srv://crpyto_exchange:XuyM9bh6vJUx49Vv@cluster0.hfbt1.mongodb.net/crpyto_exchange?retryWrites=true&w=majority
      database: crpyto_exchange

server:
  port: 8080
  servlet:
    contextPath: /crpyto-service

in-memory-cache:
  size: 10000 #different methods response which can be cached
  ttl: PT10M # 10 Minutes

rest-client:
  binance:
    connection-timeout: PT5S
    read-timeout: PT10S
retry-template:
  back-off-period: PT1S
  max-rety: 2
thread-pool:
  count: 21
email-service:
  api-key: 600E9BC0A7DC168EAB8F0C9038592867CA6DDAA91D6052EB8CDFEA73B99009A61A41C0DD905FD85248A7F3079CC0C578
  url: https://api.elasticemail.com/v2/email/send
vendors:
  binance:
    scheme: ${BINANCE_SCHEME:https}
    host: ${BINANCE_HOST:api1.binance.com}
    path-segment: api/v3
    exchange-list:
      path: exchangeInfo
    klines:
      path: klines
exchange:
  expiry: 3
crons:
  exhange-symbol:
    init-delay: PT2S
    periodic-gap: PT24H
  candlesticks:
    init-delay: PT1S
    periodic-gap: PT1M