spring:
  application:
    name: CrpytoService
  data:
    mongodb:
      uri: mongodb+srv://crpyto_exchange:XuyM9bh6vJUx49Vv@cluster0.hfbt1.mongodb.net/crpyto_exchange?retryWrites=true&w=majority
      database: crpyto_exchange

server:
  port: 8080
  servlet:
    contextPath: /crpyto-service

in-memory-cache:
  size: 10000 #different methods response which can be cached
  ttl: PT10M # 10 Minutes

rest-client:
  binance:
    connection-timeout: PT5S
    read-timeout: PT10S
retry-template:
  back-off-period: PT1S
  max-rety: 2
thread-pool:
  count: 21